In [1]:
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('/content/drive/My Drive/Data /carprices.csv')

In [3]:
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [6]:
dummies = pd.get_dummies(df['Car Model'])

In [7]:
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [11]:
merged = pd.concat([df, dummies], axis=1)

In [12]:
merged

                Car Model  Mileage  ...  BMW X5  Mercedez Benz C class
0                  BMW X5    69000  ...       1                      0
1                  BMW X5    35000  ...       1                      0
2                  BMW X5    57000  ...       1                      0
3                  BMW X5    22500  ...       1                      0
4                  BMW X5    46000  ...       1                      0
5                 Audi A5    59000  ...       0                      0
6                 Audi A5    52000  ...       0                      0
7                 Audi A5    72000  ...       0                      0
8                 Audi A5    91000  ...       0                      0
9   Mercedez Benz C class    67000  ...       0                      1
10  Mercedez Benz C class    83000  ...       0                      1
11  Mercedez Benz C class    79000  ...       0                      1
12  Mercedez Benz C class    59000  ...       0                      1

[13 rows x 7 columns]

In [18]:
final = merged.drop(['Car Model', 'Mercedez Benz C class'], axis =1)

In [19]:
final

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [23]:
X = final.drop(['Sell Price($)'], axis = 1)

In [25]:
y = final['Sell Price($)']

In [26]:
reg = linear_model.LinearRegression()

In [27]:
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
reg.predict([[45000,4,0,0,]])

array([36991.31721061])

In [30]:
reg.predict([[86000,7,0,1]])

array([11080.74313219])

In [31]:
reg.score(X,y)

0.9417050937281083